USE CARTOON;

SELECT CARTOON_NAME
FROM CARTOON_BY_ID WHERE CARTOON_ID = 13;

USE DIRECTOR;

SELECT SUM(VIEWS)
FROM CARTOON_BY_DIRECTOR_ID WHERE DIRECTOR_ID = 15
ORDER BY CARTOON_NAME ASC;

USE CARTOON;

SELECT COUNT(CARTOON_NAME)
FROM CARTOON_BY_COUNTRY WHERE COUNTRY = 'France/UK';