CREATE KEYSPACE CARTOON
WITH replication = {'class': 'SimpleStrategy',
'replication_factor': 3}

CREATE KEYSPACE DIRECTOR
WITH replication = {'class': 'SimpleStrategy',
'replication_factor': 3}

CREATE TABLE CARTOON.CARTOON_BY_COUNTRY(
    COUNTRY TEXT,
    CARTOON_ID SMALLINT,
    CARTOON_NAME TEXT,
    VIEWS INT,
    PRIMARY KEY ((COUNTRY, CARTOON_ID), VIEWS)
    WITH CLUSTERING ORDER BY (VIEWS DESC)
);

CREATE TABLE CARTOON.CARTOON_BY_ID(
    CARTOON_ID SMALLINT PRIMARY KEY,
    YEAR SMALLINT,
    CARTOON_NAME TEXT,
    DURATION INT
);

CREATE TABLE DIRECTOR.DIRECTOR_BY_CARTOON_ID(
    CARTOON_ID SMALLINT,
    DIRECTOR_ID SMALLINT,
    DIRECTOR_NAME TEXT,
    PRIMARY KEY (CARTOON_ID, DIRECTOR_ID)
);

CREATE TABLE DIRECTOR.CARTOON_BY_DIRECTOR_ID(
    DIRECTOR_ID SMALLINT,
    CARTOON_ID SMALLINT,
    CARTOON_NAME TEXT,
    VIEWS INT,
    PRIMARY KEY ((DIRECTOR_ID, CARTOON_ID, CARTOON_NAME))
    WITH CLUSTERING OREDER BY (CARTOON_NAME ASC)
);

CREATE TABLE EDUCATION.COURSE(
    IdCourse SMALLINT,
    YearCourse SMALLINT,
    NameCourse TEXT,
    VIEWS INT,
    PRIMARY KEY (IdCourse, YearCourse)
);

INSERT INTO
CARTOON.CARTOON_BY_COUNTRY
(COUNYTRY, CARTOON_ID, CARTOON_NAME, VIEWS)
VALUES ('USA', 1, 'The Lion King', 5494742)

INSERT INTO
CARTOON.CARTOON_BY_ID
(CARTOON_ID, YEAR, CARTOON_NAME, DURATION)
VALUES (1, 1994, 'The Lion King', 88)

INSERT INTO
DIRECTOR.DIRECTOR_BY_CARTOON_ID
(CARTOON_ID, DIRECTOR_ID, DIRECTOR_NAME)
VALUES (1, 1, 'Rodger Allers');

INSERT INTO
DIRECTOR.DIRECTOR_BY_CARTOON_ID
(CARTOON_ID, DIRECTOR_ID, DIRECTOR_NAME)
VALUES (1, 2, 'Rob Minkoff');

INSERT INTO
DIRECTOR.CARTOON_BY_DIRECTOR_ID
(DIRECTOR_ID, CARTOON_ID, CARTOON_NAME, VIEWS)
VALUES (1, 1, 'The Lion King', 5494742);

INSERT INTO
DIRECTOR.CARTOON_BY_DIRECTOR_ID
(DIRECTOR_ID, CARTOON_ID, CARTOON_NAME, VIEWS)
VALUES (2, 1, 'The Lion King', 5494742);

USE CARTOON;

SELECT CARTOON_NAME, VIEWS
FROM CARTOON_BY_COUNTRY WHERE COUNTRY = 'USA'
ORDER BY VIEWS DECS;

USE CARTOON;

SELECT DURATION, YEAR
FROM CARTOON_BY_ID WHERE CARTOON_ID = 3;

USE DIRECTOR;

SELECT DIRECTOR_NAME
FROM DIRECTOR_BY_CARTOON_ID WHERE CARTOON_ID = 3;

USE DIRECTOR;

SELECT CARTOON_NAME, VIEWS
FROM CARTOON_BY_DIRECTOR_ID WHERE DIRECTOR_ID = 10
ORDER BY CARTOON_NAME ASC;